# Generated by Django 4.2.6 on 2023-10-25 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='appdes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appname', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, null=True)),
                ('appshorts', models.CharField(default='', max_length=255)),
                ('appdescription', models.TextField(blank=True, null=True)),
                ('appdescriptionextra', models.TextField(blank=True, null=True)),
                ('appimage', models.ImageField(null=True, upload_to='image')),
                ('appimageurl', models.URLField(null=True)),
                ('appothercats', models.TextField(blank=True, null=True)),
                ('appeditorchoice', models.CharField(blank=True, choices=[('EDITORSCHOICE', 'Editors_Choice')], max_length=100, null=True)),
                ('appcat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pittappsapi.category')),
            ],
        ),
    ]
