# Generated by Django 4.2.6 on 2023-10-25 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pittappsapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appdes',
            old_name='appname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='catname',
            new_name='name',
        ),
    ]
