# Generated by Django 4.2.6 on 2023-10-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pittappsapi', '0002_rename_appname_appdes_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appdes',
            name='appimage',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='appdes',
            name='appimageurl',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appdes',
            name='appshorts',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
