# Generated by Django 4.2.6 on 2023-10-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pittappsapi', '0004_rename_name_appdes_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appdes',
            name='appshorts',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='appdes',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
