# Generated by Django 4.2.6 on 2023-10-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pittappsapi', '0005_alter_appdes_appshorts_alter_appdes_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appdes',
            name='appimageurl',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
